from setuptools import find_packages, setup

setup(
    name="metaos",
    version="0.0.0",
    packages=find_packages(
        where=".",
        include=[
            "app",
            "artifact",
            "domains",
            "genesis",
            "metaos",
            "metaos_a",
            "metaos_b",
            "metaos_c",
            "runtime",
            "validation",
            "observer",
            "signal",
            "strategy",
            "ecosystem",
            "federation",
            "evolution",
            "core",
            "kernel",
            "loop",
        ],
    ),
)
