from __future__ import annotations

from typing import Protocol


class TemplateDomainContract(Protocol):
    def input(self) -> dict: ...
    def generate(self) -> dict: ...
    def evaluate(self, artifact: dict) -> dict: ...
    def metrics(self, artifact: dict) -> dict: ...
    def loop(self) -> dict: ...
    def resources(self) -> dict: ...
    def genome(self) -> dict: ...
