from __future__ import annotations

from typing import Any, Protocol


class DomainContract(Protocol):
    def input(self) -> dict[str, Any]: ...
    def generate(self) -> dict[str, Any]: ...
    def evaluate(self, artifact: dict[str, Any]) -> dict[str, Any]: ...
    def metrics(self, artifact: dict[str, Any]) -> dict[str, float]: ...
    def loop(self) -> dict[str, Any]: ...
    def resources(self) -> dict[str, Any]: ...
    def genome(self) -> dict[str, Any]: ...
